## Put defined MCU peripherals here (in alphabetical order)
## -jmhe-moved to cpu.

# The board MPU family (used for grouping by the CI system)
FEATURES_MCU_GROUP = cortus_aps

-include $(RIOTCPU)/cortus_aps/Makefile.features
